[reactController] remove motionPlan , read trajectories directly from port
robotology-playground/react-control pull request #19
Opened 2017-03-20 15:42 UTC by towardthesea

The main purpose of this `PR` is:
- Remove `motionPlan` dependency 
- Introduce 1 new method to read trajectories from `planner` directly from port.

It is tested on simulation. The behavior of integration is the same!

cc @matejhof @pattacini

2017-03-20 15:43 UTC, alecive commented
I cannot say anything about the implementation, but big :+1: about the design decision of decoupling the two parts of the software.

2017-03-21 10:28 UTC, pattacini requested changes
Aside from one doubt on dynamic allocation of resources, I've noticed that you changed the reading paradigm from **callback** to **polling**. Is that wanted / correct?

2017-03-21 10:28 UTC, pattacini commented on modules/reactController/src/reactCtrlThread.cpp
> +                    ControlPoint *ctrlPt = new ControlPoint();
@towardthesea where is this dynamic object `ctrlPt` finally deallocated?

2017-03-21 12:59 UTC, pattacini commented on modules/reactController/src/reactCtrlThread.cpp
> +                    delete ctrlPt;
That's wrong...

2017-03-21 14:43 UTC, pattacini approved these changes

2017-03-21 14:43 UTC, merged

2017-03-21 14:49 UTC, towardthesea commented
Regarding the **callback** vs **polling** question, `motionPlan` was designed with callback for the communication between `planner` and `supervisor`, which is asynchronous. In case of `react-controller`, the reference update is synchronous.